name: Flutter Build

on:
  push:
    branches: [ master ]
  workflow_dispatch:

env:
  PROJECT_ROOT: src/trammy

jobs:
  build-android:
    runs-on: ubuntu-latest
    name: Build Flutter Android
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Install dependencies
        run: flutter pub get
        working-directory: ${{ env.PROJECT_ROOT }}

      - name: Run Flutter analyze
        run: flutter analyze
        working-directory: ${{ env.PROJECT_ROOT }}

      - name: Build APK
        run: flutter build apk --debug
        working-directory: ${{ env.PROJECT_ROOT }}

