name: Flutter

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PROJECT_ROOT: src/trammy
  
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v4
        with:
          channel: stable
          version: 3.41.2

      - name: Install dependencies
        run: flutter pub get
        working-directory: ${{ env.PROJECT_ROOT }}

      - name: Build debug
        run: flutter build apk --debug
        working-directory: ${{ env.PROJECT_ROOT }}
